name: Playwright Tests
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  playwright-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
      - name: Run Playwright Tests
        shell: devenv shell bash -- -e {0}
        run: |
          pnpm install
          pnpm dlx playwright install --with-deps
          pnpm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
